spring:
  profiles:
    active:
      - dev
mybatis:
  configuration:
    # 驼峰命名
    map-underscore-to-camel-case: true
  mapper-locations: mybatis/**/*Mapper.xml
  type-aliases-package: top.yalexin.rblog.entity.*
# pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql