spring:
  profiles:
    active:
      - dev
  mail:
    username: 495592364@qq.com
    # 授权码，不是QQ登录密码
    password:
    host: smtp.qq.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
            socketFactory:
              port: 465
              class: javax.net.ssl.SSLSocketFactory
    port: 465
    protocol: smtp
    default-encoding: utf-8

mybatis:
  mapper-locations: classpath:mybatis/*Mapper.xml
  config-location: classpath:mybatis/mybatis-config.xml



########## 自定义 ############
# 是否开启邮件通知被回复的层主
comment_email_enable: true
# 是否开启邮件通知博主
comment_email_self_enable: true

blog_host: www.yalexin.top/blog
blogger_nickname: 黄阿信
# 发送邮件的邮箱
email_from: 495592364@qq.com
# 接收通知邮件的邮箱
email_receive: 495592364@qq.com

#html template path (resources/templates/email/template.html)
templatePath: email/template

# POW 验证码相关
pow-difficulty: 5
pow-prefix-length: 8
