logging:
  level:
    root: info
    top:
      yalexin:
        rblog:
          mapper: debug
  file:
    name: log/blog-dev.log
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&useJDBCCompliantTimezoneShift=true&useUnicode=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
server:
  address: 0.0.0.0
  servlet:
    context-path: /api