spring:
  profiles:
    active:
      - dev
mybatis:
  mapper-locations: classpath:mybatis/*Mapper.xml
  config-location: classpath:mybatis/mybatis-config.xml


# pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql